<?php


class Base_level extends BaseModel
{
    public function tableName()
    {
        return '{{x2_base_level}}'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return array(
            array('F_CODE,F_NAME', 'required', 'message' => '{attribute} 不能为空'),
            array($this->safeField(),'safe',),
        );
    }
    public function attributeLabels()
    {
        return array(
            'F_CODE'=>'年级编码',
            'F_NAME'=>'年级名称',
            'F_LENAME'=>'年级英文名称',
            'F_LSNAME'=>'年级简称',
            'F_LLNAME'=>'年级中文全名',
            'F_PNAME'=>'年级阶段',
            'F_value'=>'年级短名称',
            'F_TYPE'=>'分类类型',
            'F_COL1'=>'表单位置1',
            'F_COL2'=>'表单位置2',
            'F_COURSECODE'=>'课程编码最小代码',
            'F_SPARE'=>'余暇课程',
            'F_TREM'=>'毕业学期',
        ); // TODO: Change the autogenerated stub
    }
    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }
    
   public function downSelect($form,$m,$atts,$onchange='',$noneshow=''){
     $data=$this->findAll('1 order by F_CODE');
     return BaseLib::model()->selectByData($form,$m,$atts,$data,'F_NAME',$onchange,$noneshow);
    }

}